cursor            #a4c9fe
cursor_text_color #00315d

foreground            #e1e2e9
background            #0c0e13
selection_foreground  #263141
selection_background  #bcc7db
url_color             #bcc7db

#: black 000000 767676
color0  #111318
color8  #32353a
#: red cc0403 f2201f
color1  #702728
color9  #ca6668
#: green 19cb00 23fd00
color2  #bcc7db
color10 #d8e3f8
#: yellow cecb00 fffd00
color3  #d9bde3
color11 #f6d9ff
#: blue 0d73cc 1a8fff
color4  #204876
color12 #a4c9fe
#: magenta cb1ed1 fd28ff
color5  #3d4758
color13 #bcc7db
#: cyan 0dcdcd 14ffff
color6  #543f5e
color14 #d9bde3
#: white dddddd ffffff
color7  #c3c6cf
color15 #e1e2e9

mark1_foreground #001c39
mark1_background #d4e3ff
mark2_foreground #111c2b
mark2_background #d8e3f8
mark3_foreground #271430
mark3_background #f6d9ff

active_tab_foreground #00315d
active_tab_background #a4c9fe
inactive_tab_foreground #d4e3ff
inactive_tab_background #204876

active_border_color #a4c9fe
inactive_border_color #00315d
# bell_border_color #ff5a00
