cursor            #fab1da
cursor_text_color #511e3f

foreground            #eddfe4
background            #130c10
selection_foreground  #402a36
selection_background  #debecd
url_color             #debecd

#: black 000000 767676
color0  #181115
color8  #3b3236
#: red cc0403 f2201f
color1  #1d2d4c
color9  #486fba
#: green 19cb00 23fd00
color2  #debecd
color10 #fcd9e9
#: yellow cecb00 fffd00
color3  #f4ba9d
color11 #ffdbcb
#: blue 0d73cc 1a8fff
color4  #6b3456
color12 #fab1da
#: magenta cb1ed1 fd28ff
color5  #58404d
color13 #debecd
#: cyan 0dcdcd 14ffff
color6  #653d27
color14 #f4ba9d
#: white dddddd ffffff
color7  #d3c2c9
color15 #eddfe4

mark1_foreground #370729
mark1_background #ffd8eb
mark2_foreground #291521
mark2_background #fcd9e9
mark3_foreground #311303
mark3_background #ffdbcb

active_tab_foreground #511e3f
active_tab_background #fab1da
inactive_tab_foreground #ffd8eb
inactive_tab_background #6b3456

active_border_color #fab1da
inactive_border_color #511e3f
# bell_border_color #ff5a00
