[config]
fallback_color = "#FFFFAA"
prefere = "saturation"

[config.wallpaper]
set = true
command = "awww img --transition-type center {{ image }}"

[templates.hyprland]
input_path = 'templates/hyprland-colors.lua'
output_path = '~/.config/hypr/hyprland-colors.lua'

[templates.kitty]
input_path = 'templates/kitty-colors.conf'
output_path = '~/.config/kitty/kitty-colors.conf'

[templates.tmux]
input_path = 'templates/tmux-colors.conf'
output_path = '~/.config/tmux/tmux-colors.conf'
post_hook = 'tmux source-file ~/.config/tmux/generated.conf' 

[templates.ghostty]
input_path = 'templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'
