-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ./hyprland-colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
-- require("hyprland-colors")
local color1 = primary or "rgba(33ccffee)"
local color2 = secondary or "rgba(00ff99ee)"
local color3 = "rgba(ffffff00)"
-- $color1 = rgba(33ccffee) 
-- $color2 = rgba(00ff99ee)
-- $color3 = rgba(00ff00ff)

-- #######################################################################################
-- AUTOGENERATED HYPR CONFIG.
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- autogenerated = 1 # remove this line to remove the warning

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- monitor=,preferred,auto,auto
hl.monitor({
    output = "",
    mode = "1920x1080@144",
    position = "0x0",
    scale = "1.2",
})

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use
local term = "kitty"
local terminal = "kitty fish -c ta"
local fileManager = "dolphin"
local browser = "firefox"
local emacs = "emacsclient -c"
local menu_wofi = "wofi --show drun"
local menu_rofi = "rofi -show drun"
local menu_tofi = "kitty -e \"$(tofi-run)\""
local menu = menu_rofi

--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- Open applications
-- exec-once = [workspace special:steam silent] steam 

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1.0 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 5.39,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.79,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    bezier = "easeOutQuint",
    style = "popin 87%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.49,
    bezier = "linear",
    style = "popin 87%",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.73,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.46,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.81,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "easeOutQuint",
    style = "fade",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.5,
    bezier = "linear",
    style = "fade",
})
hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(term))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("wlogout"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exit())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))

hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("wofi --show drun"))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("tofi-run"))
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("qutebrowser"))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd(emacs))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy"))
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + F1", hl.dsp.exec_cmd("firefox https://wiki.hypr.land/Configuring/Window-Rules"))
hl.bind(mainMod .. " + F2", hl.dsp.exec_cmd("kitty nvim ~/.config/hypr/hyprland.conf"))
hl.bind(mainMod .. " + F5", hl.dsp.exec_cmd("~/dotfiles/utils/matugen.sh"))
hl.bind(mainMod .. " + F7", hl.dsp.exec_cmd("noctalia-shell kill; noctalia-shell &"))
hl.bind(mainMod .. " + F8", hl.dsp.exec_cmd("~/.config/hypr/gamemode.sh"))

hl.bind("CTRL + SHIFT + 8", hl.dsp.exec_cmd("hyprctl switchxkblayout keyd-virtual-keyboard 1"))
hl.bind("CTRL + SHIFT + 9", hl.dsp.exec_cmd("hyprctl switchxkblayout keyd-virtual-keyboard 0"))

hl.bind(mainMod .. " + T", hl.dsp.submap("tiling"))
-- TODO: manual review — wrap the following binds in hl.define_submap("tiling, reset", function() ... end). The next 'submap = reset' closes the block.
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + T", hl.dsp.layout("togglesplit, "))
hl.bind(mainMod .. " + F", hl.dsp.layout("swapwithmaster, master"))
-- (end of submap block)

hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "d" }))

hl.bind("SUPER + CTRL + h", hl.dsp.layout("preselect l"))
hl.bind("SUPER + CTRL + j", hl.dsp.layout("preselect d"))
hl.bind("SUPER + CTRL + k", hl.dsp.layout("preselect u"))
hl.bind("SUPER + CTRL + l", hl.dsp.layout("preselect r"))
hl.bind("SUPER + CTRL + Space", hl.dsp.layout("preselect cancel"))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind(mainMod .. " + grave", hl.dsp.focus({ workspace = "name:games" }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.workspace_rule({
    workspace = "1",
    -- TODO: manual review — workspace field "default"
})

hl.workspace_rule({
    workspace = "10",
    layout = "scrolling",
})

hl.window_rule({
    name = "steam-special-workspace",
    match = {
        class = "steam",
    },
    workspace = "special:steam silent",
})

hl.window_rule({
    name = "games-out-of-steam-workspace",
    match = {
        workspace = "special:steam",
        class = "negative:steam",
    },
    workspace = "name:games",
})

hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize activate activateFocus",
})

hl.layer_rule({
    match = { namespace = "match:namespace logout_dialog" },
    -- TODO: manual review — unmapped layer rule: "blur on"
})

local scratchpadSize = "size (monitor_w*0.8) (monitor_h*0.8)"

-- hl.workspace_rule({
--     workspace = "special:terminal",
--     ["on-created-empty"] = "[float; " .. scratchpadSize .. "] kitty",
--     persistent = false,
-- })
--
-- hl.workspace_rule({
--     workspace = "special:nh",
--     ["on-created-empty"] = "[float; " .. scratchpadSize .. "] kitty ~/dotfiles/utils/nh.sh",
--     persistent = false,
-- })
--
-- hl.workspace_rule({
--     workspace = "special:spotify",
--     ["on-created-empty"] = "[float; " .. scratchpadSize .. "] kitty ncspot",
--     persistent = false,
-- })
--
-- hl.workspace_rule({
--     workspace = "special:impala",
--     ["on-created-empty"] = "[float; " .. scratchpadSize .. "] kitty impala",
--     persistent = false,
-- })
--
-- hl.workspace_rule({
--     workspace = "special:steam",
--     ["on-created-empty"] = "[float; " .. scratchpadSize .. "] steam",
--     persistent = false,
-- })
--
-- hl.workspace_rule({
--     workspace = "special:kdeconnect",
--     ["on-created-empty"] = "[float; " .. scratchpadSize .. "] kdeconnect-app",
--     persistent = false,
-- })
--
-- hl.workspace_rule({
--     workspace = "special:bluetui",
--     ["on-created-empty"] = "[float; " .. scratchpadSize .. "] kitty bluetui",
--     persistent = false,
-- })
--
-- hl.workspace_rule({
--     workspace = "special:btop",
--     ["on-created-empty"] = "[float; " .. scratchpadSize .. "] kitty btop",
--     persistent = false,
-- })
--
-- hl.workspace_rule({
--     workspace = "special:hyprland",
--     ["on-created-empty"] = "[float; " .. scratchpadSize .. "] kitty nvim ~/dotfiles/hypr/hyprland.conf",
--     persistent = false,
-- })

hl.bind(mainMod .. " + S", hl.dsp.submap("scratchpads"))
-- TODO: manual review — wrap the following binds in hl.define_submap("scratchpads, reset", function() ... end). The next 'submap = reset' closes the block.
hl.define_submap("scratchpads, reset", function()
	hl.bind(mainMod .. " + P", hl.dsp.workspace.toggle_special("spotify"))
	hl.bind(mainMod .. " + U", hl.dsp.workspace.toggle_special("nh"))
	hl.bind(mainMod .. " + Y", hl.dsp.workspace.toggle_special("terminal"))
	hl.bind(mainMod .. " + I", hl.dsp.workspace.toggle_special("impala"))
	hl.bind(mainMod .. " + G", hl.dsp.workspace.toggle_special("steam"))
	hl.bind(mainMod .. " + K", hl.dsp.workspace.toggle_special("kdeconnect"))
	hl.bind(mainMod .. " + B", hl.dsp.workspace.toggle_special("bluetui"))
	hl.bind(mainMod .. " + M", hl.dsp.workspace.toggle_special("btop"))
	hl.bind(mainMod .. " + H", hl.dsp.workspace.toggle_special("hyprland"))
	hl.bind("catchall", hl.dsp.submap("reset"))
end)
-- (end of submap block)

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 1,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
        -- col.inactive_border = rgba(595959aa)
        col = {
            -- active_border = color1 .. " " .. color2 .. " 45deg",
        },
        -- col.inactive_border = $background $color0 45deg
        -- col.inactive_border = $background
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        no_focus_fallback = true,
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#decoration
    decoration = {
        rounding = 10,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1,
        inactive_opacity = 1,
        dim_inactive = true,
        dim_strength = 0.2,
        shadow = {
            enabled = true,
            range = 20,
            render_power = 4,
            -- color = rgba(1a1a1aee)
            -- color_inactive = rgb(00ff00)
            color = color1,
            -- color_inactive = rgba(00ffee00)
            color_inactive = color3,
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 4,
            passes = 3,
            new_optimizations = true,
            ignore_opacity = true,
            noise = 0,
            brightness = 1.0,
            -- vibrancy = 0.1696
            vibrancy = 0.3,
            vibrancy_darkness = 0,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#animations
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
    -- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
    -- "Smart gaps" / "No gaps when only"
    -- uncomment all if you wish to use that.
    -- workspace = w[tv1], gapsout:0, gapsin:0
    -- workspace = f[1], gapsout:0, gapsin:0
    -- windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
    -- windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
    -- windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
    -- windowrulev2 = rounding 0, floating:0, onworkspace:f[1]
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    dwindle = {
        preserve_split = true, -- You probably want this
        force_split = 2,
    },
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master = {
        new_status = "slave",
        new_on_top = true,
        mfact = 0.70,
    },
    -- See https://wiki.hyprland.org/Configuring/Scrolling-Layout/ for more
    scrolling = {
        fullscreen_on_one_column = false,
        column_width = 0.95,
        focus_fit_method = 0,
    },
    cursor = {
        no_warps = true,
        hide_on_key_press = true,
    },
    xwayland = {
        force_zero_scaling = true,
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#misc
    misc = {
        -- force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
        -- disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
        focus_on_activate = true,
        enable_swallow = true,
        swallow_regex = "(scratch_term)|(Alacritty)|(kitty)",
    },
    --############
    --## INPUT ###
    --############
    -- https://wiki.hyprland.org/Configuring/Variables/#input
    input = {
        kb_layout = "us,fi",
        kb_variant = "",
        kb_model = "",
        -- kb_options = ctrl:nocaps # Done on system level
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
    -- TODO: Change language on keypress
    -- https://wiki.hypr.land/Configuring/Using-hyprctl/#switchxkblayout
    -- Example per-device config
    -- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
    --##################
    --## KEYBINDINGS ###
    --##################
    -- See https://wiki.hyprland.org/Configuring/Keywords/
    -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
    -- Language binds
    -- Layout binds
    -- Move focus with mainMod + arrow keys
    -- Window preselect
    -- Switch workspaces with mainMod + [0-9]
    -- Move active window to a workspace with mainMod + SHIFT + [0-9]
    -- Scroll through existing workspaces with mainMod + scroll
    -- Move/resize windows with mainMod + LMB/RMB and dragging
    -- Laptop multimedia keys for volume and LCD brightness
    -- Requires playerctl
    -- Shaders
    -- bind=SUPER_CTRL,s,exec,hyprctl keyword decoration:screen_shader "$(find $HOME/.config/hypr/shaders/ | grep "frag" | rofi -dmenu)"
    -- NOTE: does not work
    -- bind=SUPER_CTRL,s,exec, ~/.config/hypr/shaders/updateShader.sh
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
    -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
    -- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
    -- NOTE: use "hyprctl clients" or "hyprctl activewindow" for classes, titles, etc.
    -- Set workspace 1 as default
    -- Set workspace 9 as a scrolling layout
    -- Applies to all games lauched from steam GUI
    -- Not those run from a launcher / rofi
    -- TODO: figure out a unified way to handle games / steam
    -- Ignore maximize requests from apps. You'll probably like this.
    -- apply blur for wlogout window
    --########################
    --## Scratchpad config ###
    --########################
    -- TODO: hyprsunset
})

hl.on("hyprland.start", function()
    hl.exec_cmd("wal -R -s &")
    hl.exec_cmd("awww-daemon &")
    hl.exec_cmd("noctalia-shell")
    hl.exec_cmd("emacs --daemon")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("wl-paste --type text  --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd(terminal, { workspace = "1 silent" })
    hl.exec_cmd(browser, { workspace = "2 silent" })
    hl.exec_cmd(emacs .. " -a 'emacs'", { workspace = "9 silent" })
    hl.exec_cmd("qutebrowser", { workspace = "10 silent" })
end)

