require('modules.variables') -- Maybe just move variables to this file
require('modules.colors')
require('modules.binds')
require('modules.rice')
require('modules.config')
require('modules.hardware')
require('modules.autostart')
require('modules.rules.layers')
require('modules.rules.windows')
require('modules.rules.workspaces')
